server:
  port: 8082
spring:
  resources:
    static-locations:
      - classpath:resources
      - classpath:static
  mvc:
    view:
      # \u9875\u9762\u9ED8\u8BA4\u524D\u7F00\u76EE\u5F55
      prefix: /WEB-INF/JSP/
      # \u54CD\u5E94\u9875\u9762\u9ED8\u8BA4\u540E\u7F00
      suffix: .jsp
